### ISSUE TITLE
error during load_json with retinanet model

### ISSUE THREAD

**Issue by Jugaris89** [Dobiasd/frugally-deep#219]
hi @Dobiasd ,

very good work, thanks!

I am having an issue porting my keras_retinanet model to c++. I have checked the frugally version and tensorflow version and they are: 
v0.11.0-p0
2.0.0
2.2.4-tf
respectively.

I have seen there is a similar issue answered in the FAQ section. I followed the steps you commented but I still have the issue. Hope you can help me.

Here is what i do:
- I trained my keras_retinanet with training_model.fit_generator(..) and then training_model.save('frugally_model.h5', include_optimizer=False)

- once the h5 model is saved, I convert it as follows:  python3 convert_model.py frugally_model.h5 model.json. 
The only modification i did was changing: "from tensorflow.keras.models import Model, load_model" -->  from tensorflow.keras.models import Model
from ..models import load_model

to avoid issue: TypeError: ('Keyword argument not understood:', 'freeze'). The rest is the same.

- I compile the main.cpp that only load the json: g++ -I ../../../frugally-deep/eigen3/ -std=c++14 -O3 ./main.cpp -o out

I get following error: 
 ./out
Loading json ... done. elapsed time: 1.544799 s
Building model ... terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is number
Aborted (core dumped)

NOTE: in main.cpp I had to put "#define NDEBUG" before the include section to avoid the error:  Assertion `m_value.object->find(key) != m_value.object->end()' failed.

hope you could check it and give me a hint where the problem might be.

thanks in advance

**Comment by Dobiasd** [comment]
Hi, and thanks for the very good report. Could you upload your `.h5` file so I can try to reproduce the error locally?

**Comment by Jugaris89** [comment]
I put here a link to Gdrive since it is too big to be attached.

Thanks again for the help.

https://drive.google.com/file/d/1gnn8EVpS-lKXsEaAXUX_uDnRmkk-dM7Q/view?usp=sharing

**Comment by Dobiasd** [comment]
Yes, I also get `TypeError: ('Keyword argument not understood:', 'freeze')`.

There are some `custom objects`, I guess. Can you show how its architecture is created?
And what's the `from ..models import load_model` part you are doing?

**Comment by Jugaris89** [comment]
the load model function is imported from keras retinanet, like here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py
when using this load function, there are custom objects loaded that prevent the issue of "TypeError: ('Keyword argument not understood:', 'freeze')"

the architecture is defined here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/retinanet.py
all layers from retinanet were already developed in your framework except "upsampleLike" layer which i implemented (similar purpose as upsampling2D)

thanks for your help.

**Comment by Jugaris89** [comment]
hi,
do you have an idea how could i solve it? how could i avoid the custom objects or try to load the model with them?
thanks!

**Comment by Dobiasd** [comment]
I've not solved it yet, but if you somehow manage to do without (or remove) the custom object, that would make things simple. Basically, if you can load your model with `tensorflow.keras.models.load_model` it should work fine.

**Comment by Dobiasd** [comment]
Ah, I see, this custom object is the "backbone" of the model. Is can not simply be removed. :grin:

Maybe there is a way to "flatten" the nested models into one so that the custom object would be "inlined" and no longer treated explicitly further on?

**Comment by Abdiflame** [comment]
I am having the same problem here :( 

My model is an LRCN, the architecture is as follows: 
the input_2 (InputLayer) is an VGG_16 followed by GlobalAveragePooling2D().

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 8, 123, 224, 3)    0         
_________________________________________________________________
time_distributed_1 (TimeDist (None, 8, 512)            14714688  
_________________________________________________________________
time_distributed_2 (TimeDist (None, 8, 512)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 512)               2099200   
_________________________________________________________________
dense_1 (Dense)              (None, 128)               65664     
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 258       
=================================================================

**Comment by Dobiasd** [comment]
Thanks for the report and for uploading the model file. I'm currently afk for two weeks. I'll look into it as soon as I'm back.

**Comment by Abdiflame** [comment]
> Thanks for the report and for uploading the model file. I'm currently afk for two weeks. I'll look into it as soon as I'm back.

Alright, since my issue seems like an "important" problem, I will make a new issue post for it. Thanks in advance :)

**Comment by Dobiasd** [comment]
Closing this issue due to inactivity.

@Jugaris89 if this is still a problem, or if you found out how to solve it, please let me know. :slightly_smiling_face:
